### PR TITLE
Update PlaySource

### PR DESCRIPTION
**Pull request by Makuna**

### CODE REVIEW

**Comment by ghmartin77** [comment]
Hi Makuna,

Firstly thanks for your quick reaction on my issues filed. Unfortunately I think the changes applied are not working as intended.
The API of the player is not symmetrical, i.e. setPlaybackSource (command 0x09) and player messages on events like USB inserted/removed, SD card inserted/removed (messages 0x3F, 0x3A, 0x3B) do not use the same ID's to identify the same things. For 0x09 it is indeed just a number identifying the source to play from. For 0x3F the replied argument is a bitset where the bit values of entries for USB and SD card coincidentally are matching the values from playsource. For 0x3A and 0x3B it could be a bitfield as well, while it doesn't make much sense as adding/removing things at exactly the same time seems virtually impossible.

Conclusion: PlaybackSource used for 0x09 and replies for 0x3A, 0x3B, 0x3F shouldn't be mixed.

BR,
ghmartin77

**Comment by Makuna** [comment]
I disagree.

One, the only spec that even states that they are value rather a bit field contradicts itself on the values used.
At this section, USB would be zero, not 1.  

image

But later in the same spec, the example of use for that command has 1 for USB.  

image

The only available spec documents this command to support a 1 and 2 values which could be both ways (a value range or a bitfield) except for one crucial point. Values are zero based.  See the 0x07 command, first option starts with zero.  So I can only assume its a bit field and it matches other uses for the same play source.
Now, the one less consistent spec (as noted above) documents a sleep. of which when I tried it I could not find what this does and I am more than likely just going to remove it for consistency.  There is already a sleep command separately.

**Comment by ghmartin77** [comment]
Well, of course you have a point when talking about the (same) values 0x01 USB and 0x02 SD for both PlaybackSource and argument bit field values of 0x3A, 0x3B, 0x3F.
However, I'm talking about design perspective why I wouldn't mix these two things.

1. Command 0x09 in your first reference talks about values 0, 1, 2, 3, 4 which indicates values, not bit set while still having this off-by-one error as you noted. It should be 1, 2, 3, 4, 5 respectively. This off-by-one is also backed by the other quotes in the examples of chapter 3.4.3. One of the examples however is for value 5. If it would be a bit field, value 5 would be invalid (or mean playback simultaniously from USB and AUX), but it is used for playback device SLEEP. Whatever SLEEP in that context means, especially as there is a command 0x0A for exactly that purpose :) Even more crazy, actually 5 would be FLASH anyway...

2. Please also have a quick look into what is supposedly some kind of reference library implementation: https://github.com/DFRobot/DFRobotDFPlayerMini/blob/master/DFRobotDFPlayerMini.h#L27, https://github.com/DFRobot/DFRobotDFPlayerMini/blob/master/DFRobotDFPlayerMini.cpp#L323, https://github.com/DFRobot/DFRobotDFPlayerMini/blob/master/examples/FullFunction/FullFunction.ino#L62

--> Conclusion up to this point: Pretty sure Playbacksource used with comman 0x09 is not a bit set. (However, the spec is totally confusing about what exactly is meant by (0), 1, 2, 3, 4, (5) each.)

Moving on to message/command 0x3F: This one most likely is a bit set, as the spec says 1 means "USB stick online", 2 means "SD card online", 3 (as in 1+2) means "USB stick and SD card online", 4 means "PC online" (actually USB port is connected to an active USB host controller (e.g. PC), no USB stick). At least for values 1, 2, 3 this has the notion of a bit set. No example whether 6 would mean "PC connected and SD card online" or 5 being an invalid value as there is only one USB port available.

However, if you use the value reported by 0x3F and feed it as type Playbacksource into the callback method, design gets nasty: You might receive a value of 3 which means USB and SD online, but value 3 of Playbacksource is AUX.

--> Total conclusion still: Don't mix Playbacksource for 0x09 command and replies of 0x3A, 0x3B, 0x3F.

Makes sense?

**Comment by Makuna** [comment]
What is sleep and what is aux?  Both of these are completely missing from other specs (the ones that DONT have errors)?  If I removed them from Playsource, they become the same.   Again, I think you missed the point of what is the value of set play source ZER0.  Every value set in the command set starts at zero; but it really doesn't seem like a valid value for set play source.

```
enum DfMp3_PlaySource // bitfield - more than one can be set
{
    DfMp3_PlaySource_Usb = 0x01,
    DfMp3_PlaySource_Sd = 0x02,
    DfMp3_PlaySource_Pc = 0x04, 
    DfMp3_PlaySource_Flash = 0x08,
};
```

**Comment by ghmartin77** [comment]
Actually I also don't know what Playsources AUX, SLEEP and FLASH are in real live. There's nothing on the board to access AUX or FLASH. However, these are listed in your screenshot above and part of several library implementations out there. What might be possible, is that there are pins on the chip to attach AUX (the common cinch input source in several devices) and a FLASH memory chip. However, from the ready-made board most of us are using they're not accessible.
I agree, that 0 is no valid value for a Playsource. You can send it to at least YX5200-24SS and MH2024K-24SS without getting an error. However, I'm not sure if it is processed in any way. One might test this by activating ACK mode and check for a reply. Even if ACK'd I can't say what it does within the chip.

I like your "If I remove the nonesense stuff from Playsource, they become the same" argumentation. If you have a look into that spec document I referred to as probably the most correct one you could get in one of the issues (https://github.com/PowerBroker2/DFPlayerMini_Fast/blob/master/extras/FN-M16P%2BEmbedded%2BMP3%2BAudio%2BModule%2BDatasheet.pdf), you find sentences like:

grafik
 => Good indicator, 2 for SD is correct (consistently stated in the whole document)

grafik
 => Only TWO playsources are valid, which perfectly makes sense from what is accessible via the board

grafik
 => Indicator for bit field notion of 0x3A and 0x3B commands' argument

grafik
 => Indicator for bit field notion of 0x3F commands' argument (don't ask me, why 0x1010 is stated to mean SD online (but not plus PC via USB cable) :))

There's still one glitch with putting all stuff into enum data type DfMp3_PlaySource (talking design here): Semantics: You can use USB and SD as a source for playback. But you can't use an attached PC (would be PlaySource 0x08) as a source for playback. However, if this is a valid value of the enum, it could be given with a call to setPlaySource() with no valid meaning. The player does not accept 0x08 and semantically it does make no sense in real life either.
For attaching/detaching media/devices/PCs, 0x08 is meaningful though.
The following is not valid: Connectible stuff IS_A PlaySource
Thus I still wouldn't mix these, even if values for SD and USB are the same for both.

The following would make sense however (probably does not work in C++):
```
enum PlaySource {
   USB = 0x01, SD }

enum ConnectibleStuff: PlaySource {
   PC = 0x08 }
```
...and then use PlaySource in setPlaySource() only and ConnectibleStuff in callbacks for 0x3A, 0x3B, 0x3F

Convinced? :)

**Pull request merged**
